on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: lint, test and tag
    steps:
      - uses: actions/checkout@v2
      - uses: gofrolist/molecule-action@v2
      - name: bump version and push tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
